root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

plugins:
  - search
  - sharing
  - fontsettings
  - theme-default

pluginsConfig:
  sharing:
    facebook: false
    twitter: true
    google: false
    weibo: false
    instapaper: false
    vk: false
    all:
      - twitter

variables:
  api_base_url: "https://api.solixdb.com"
  docs_url: "https://docs.solixdb.xyz"

